from __future__ import annotations
from datetime import datetime, timezone
from jinja2 import Environment, StrictUndefined, TemplateSyntaxError


def render_template(template_body: str, params: dict, template_id: str = "", version: str = "") -> str:
    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    try:
        tmpl = env.from_string(template_body)
    except TemplateSyntaxError as e:
        raise ValueError(f"模板 Jinja2 语法错误: {e}") from e

    rendered = tmpl.render(**params)

    header = (
        f"// Generated by DV_ACODE_GEN_PLATFORM\n"
        f"// Template: {template_id} v{version}\n"
        f"// Time: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
    )
    return header + rendered


def validate_template_syntax(template_body: str) -> None:
    env = Environment(undefined=StrictUndefined)
    try:
        env.parse(template_body)
    except TemplateSyntaxError as e:
        raise ValueError(f"Jinja2 语法错误: {e}") from e


def render_with_dummy_params(template_body: str, parameters: list[dict]) -> str:
    dummy = {p["name"]: f"<{p['name']}>" for p in parameters}
    return render_template(template_body, dummy)
